### ISSUE TITLE
Problem with changing buttons

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/frcurrents_pi#12]
Start on HW 3:47
Push 6 next result 9:47 - HW 3:47 +6 OK
Push 1 more next result HW 10:03 - HW 16:03 -6 OK
now push 1 previous
result HW 20:03 - HW 16:03 +4 jump to the next HW
second example same area same day
Again start on HW
push 6 next result 9:47 - HW 3:47 +6 OK
now push 1 previous
result 7:47 - HW 3:47 +4 OK but back 2 hours instead of 1
now push 2 next result 9:47 - HW 3:47 +6 OK
again 1 next result 22:33 - HW 4:33 16/09 +6 jump 1 day

**Comment by Rasbats** [comment]
Thanks @Ptizef ... Great work. I will get this in the catalog.

**Comment by Rasbats** [comment]
The PR from @Ptizef  has fixed the problem.

**Comment by Rasbats** [comment]
Dave had not had time to accept the PR for v1.9 with the first changes from @Ptizef . Closed that PR and when time is available will make a new version with the second changes from @Ptizef .

**Comment by Rasbats** [comment]
Reopening.

**Comment by Ptizef** [comment]
OK, no problem for me.
I have another commit to propose : saving the last port selected to open frcurrents_pi on it.
This has been partially coded, but doesn't work.  
Pull request coming.
JP

**Comment by Rasbats** [comment]
v1.10.0 now in the catalog.
