### ISSUE TITLE
Unable to change icons for the plugin

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/frcurrents_pi#2]
Change icons in the source code but this does not change the icons shown by OpenCPN. Even after deleting the SVG cache.
[#977](https://github.com/OpenCPN/plugins/issues/977) refers.

**Comment by schnapsy** [comment]
The "**_Arrow + FR_**" icon is now displayed correctly...
Well done !

**Comment by Rasbats** [comment]
Also on my machine. Closing.
