### ISSUE TITLE
Problem with some coefficients

### ISSUE THREAD

**Issue by schnapsy** [Rasbats/frcurrents_pi#6]
Problem with some coefficients

A user has noticed differences with respect to certain coefficients by comparing with the SHOM data which is on their online site.
https://maree.shom.fr/harbor/SAINT-MALO/coeff?date=2023-08-29

The coefficients are generally very close to what the plugin gives, except for exceptions that cause problems.

for Saint Malo,

August 24 plugin coef 89 H 10.05m, SHOM coef 49 H 9.75m.
August 8 plugin coef 93 H 10.44m, SHOM coef 64 H 10.55m.
July 9 plugin coef 95 H 10.68m, SHOM coef 74 H 10.86m.
July 25 plugin coef 88 H 9.91m, SHOM coef 52 H 9.79m.

There are also errors for the following dates as well:
Sept 6, Sept 22, Oct 6, Oct 22, Nov 5, Nov 20, 2023. Note that coef 86 often returns to these erroneous dates.

I quickly checked and the problematic dates correspond to the dates when there is only one high tide, but sometimes within a day, before or after.
In fact, this seems to correspond to the days when the plugin only sees a high tide, but there may be a one-day lag compared to the SHOM tide chart.

This user also clarified the points below.
He continued to dig a little into the question of coefficient errors.

First, he realized that the coefficients for the same day were not the same from one port to another, except in the SHOM system the coefficient is the same for all the ports of France and corresponds to the Brest tides. Indeed, the coefficients of the plugin for Brest correspond well to the SHOM coefficients, either at high tide in the morning or evening, or an average of the two. This leads me to think that the coefficients, which are not given in the Merak file, were undoubtedly calculated for each port from the tidal range of said port and this would explain the inconsistent values for the days when it is not possible to find a PM and a BM to follow or vice versa.

It should be noted that the coefficient used in the SHOM charts being standard for all French ports, the Brest reference should be used exclusively to calculate the amplitude of the currents, the reference port of each chart should only be used to scheduling.

**Comment by Rasbats** [comment]
The user is correct. I was calculating the U value for the port and from that the coefficient for the day. It will be easy to do a separate calculation for tides at Brest and a universal coefficient for the day.

Many thanks for the note.

**Comment by Rasbats** [comment]
Coefficients based on range at Brest are now used in the latest alpha package.

**Comment by schnapsy** [comment]
What I indicated is an error in the displayed time of Dunkirk in the **harmonic.idx** file
**Instead of 01:00 it says 00:41.**

I corrected this error on my file, but apparently it still appears in the file offered for download.
Just correct this error with Notepad++, at line 168

I don't know how to post an illustration here, sorry.

**Comment by schnapsy** [comment]
don't find the frcurrents-1.0-**msvc**-wx32-10-tarball...

**Comment by Rasbats** [comment]
Made another build:
Commit #8666befa18f813d0020060d30ac456faecd3b7b5 

I really need to start numbering the alpha versions.

**Comment by Rasbats** [comment]
May need to refresh the browser.

**Comment by Rasbats** [comment]
@schnapsy Can this be closed?
