### ISSUE TITLE
Hide the control dalog

### ISSUE THREAD

**Issue by propedeutique56** [Rasbats/frcurrents_pi#9]
Hi,
Very nice work and very usefull plugin.
One feedback : it would be very convenient to have the possibility to move the control dialog box in the background.
Thanks again.
Bye

**Comment by Rasbats** [comment]
_move the control dialog box in the background_

Not sure what is needed. If this is 'minimise' the box can be collapsed to just the title by dragging the top of the dialog down or bottom up. I could add a minimise button but this could confuse. Not many plugins use the minimise button.

**Comment by propedeutique56** [comment]
OK. Thanks for your respnse. It is ok like this!
Another point is that, at large scale,  there are so many arrows that the map is black , with my computer, it takes a very long time to move the map which is displayed  or to zoom in..  (ex : around Roscoff)
On these point, Juzzy (under android) is much more faster and readable.
Anyway, thanks again for your work. Unfortunatly, I am not a programmer and I can't help!
Regards.
